### ISSUE TITLE
Typed-Ecstacy Performance?

### ISSUE THREAD

**Issue by Zentendo** [Lusito/typed-ecstasy#2]
I've found this library's API to have the right combination of simplicity and expressiveness. It's also one of the few ECS libraries which support TypeScript.

I would really like to go forward and use this for my game. However, I'm concerned about performance. How does Typed-Ecstasy perform compare to other ECS libraries? Each library claims to be faster than the previous.

For example yagl/fae ecs: 

> Fast even for ECS. The eligibility to systems is computed only when components list change, and in most cases the overhead of systems eligibility will be computed once per entity, when added. Therefore there is no overhead for most iterations. Iteration is often considered as a flaw of ECS pattern.

nano-ecs
> nano-ecs was created as fork of tiny-ecs, which provides similar functionality, but tries to do much more than basic ECS (timers, 2d transforms, object pools, etc). The goal of nano-ecs is to provide only a core lightweight ECS implementation

ent-comp
> A light, fast entity-component system in Javascript. This library is the distilled result of my playing with a bunch of ECS libraries, removing what wasn't useful, and rejiggering what remained to perform well in the most important cases. Specifically it's tuned to be fast at accessing the state of a given entity/component, and looping over all states for a given component.

I would be interested in what would need to be tested in order to write benchmarks which can compare the speed of ECS entity queries/iteration.

Also are you planning on implementing object pooling at any point? Just letting you know that I'm interested in this project, and planning on using it, if that's any incentive.

Would you say this library is somewhat production-ready?

**Comment by Lusito** [comment]
Hi @Zentendo.

Yes, Entity Pooling is on the todo list. I'm currently in the process of  switching employers and even cities, so it won't happen within the next couple of weeks.

As for performance: I have not done any performance comparisons yet. This is obviously something a lot of developers are concerned about. Much more than they should. Yes, there might be better performing libraries.
I've seen ECS libraries in C/C++ performing better than the c++ version of ecstasy. But many of these better performing libraries are made for specific use-cases or cause a huge development overhead.

Both ecstasy versions (c++ and typescript), have like Ashley (which both are based upon) always focused on creating an easy to understand and powerful API, while using the features available in the respective language to get the best performance with this approach in mind.

From my experience, most performance issues people have to tackle don't happen within the ECS, but in math, physics or rendering code. An ECS with a powerful and easy to use API helps you spend less time on ECS issues and more time on actual algorithms. If, at some point, you find that one system performs badly because of the way the entities and components are processed, you can always chose to listen for entity & component events to fill your own data structure, which you can then handle in a more performant way. But this is probably going to be a very rare situation.

Keep in mind, that performance can also be very different depending on the browser ( and -version).
Currently, due to the lack of pooling, performance will probably not be good for games that create and destroy lots of entities or components in short intervals, as the garbage collector will kick in and probably cause lags.

I would be really interested in some performance tests, but creating a performance test that focus on real world problems is not an easy task, especially since it largely depends on the language you write the game in. Sure, you can easily set up some simple iteration tests, but do they really tell you anything except for how well they perform on these specific tests?

Since my game development experience in JavaScript is pretty much limited to ecstasy and the [asteroids clone](https://github.com/Lusito/typed-asteroids), I'm missing some pointers to get started.

I can tell you, however, that this approach has been used successfully on a lot of games using Ashley and the c++ version of ecstasy and I've never noticed anything performing bad that was related to the ECS.

Is it production ready? Let me answer this with a few key points:
- It is a port of a proven ECS, so lots of games have been created with a similar API.
- 100% code coverage using unit-tests, which run every time a commit is pushed (none of the other JavaScript libraries have this!)
- The API will, however, probably change a bit when pooling gets introduced (probably not too much).
- So far, I have only created one game with this port, and that was a bit rushed.

Hope this helps. Looking forward to seeing your TypeScript games. Even if you decide against ecstasy.
Cheers.

**Comment by Zentendo** [comment]
@Lusito Thanks for your swift response! Your post addressed many of my concerns, and I think I'll go forward with using typed-ecstacy. 

I'll let you know if I profile any performance issues deeply related to this library, and hope to contribute with PR requests in the future if I can. Thanks again for creating this port.

**Comment by Lusito** [comment]
No problem. Take a look at https://github.com/Lusito/typed-signals/ for communication between systems. ecstasy uses it already for its events. typed-signals is production ready.
